spring:
  # 配置数据源
  datasource:
    druid:
      # Spring Boot默认的数据源是：org.apache.tomcat.jdbc.pool.DataSource
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sbobo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 

      # 初始化配置
      initial-size: 3
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 15
      # 获取连接等待超时时间（5秒）
      max-wait: 5000
      # 连接有效性检测间隔时间，检测需要关闭的空闲连接（1分30秒）
      time-between-eviction-runs-millis: 90000
      # 连接的最小生存时间（30分钟）
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: select 1
      # 配置监控统计拦截的 filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

  # 配置 JPA
  jpa:
    properties:
      hibernate:
        hibernate:
          show-sql: true
          format_sql: true

  # JWT
  jwt:
    header: Authorization
    # 令牌前缀
    token-start-with: Bearer
    # 必须使用最少88位的Base64对该令牌进行编码
    base64-secret: Zmpqc2Q9ODcyZHNkZjIzM2OkNFJFUkZhMzIzMjQzMlJkaWHzMnIyMzk4dTMyamZra3NXMjMxM1QyMzMmKiZqZUxKRiZeKjFHTExQO0RKODk4NDNqcmUoKGlvZXdqZktKRE8zMnhjY08yS0ZLTlNmZ2hqb3AtPTFSV0VIUkVXRVc=
    # 令牌过期时间（4小时）
    token-validity-in-seconds: 14400000
    # 在线用户key
    online-key: online-token
    # 验证码
    code-key: code-key